
'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import './css/heroanimation.css'
import './css/style.css'
import './vendor/bootstrap/css/bootstrap.css'
import './vendor/bootstrap/css/bootstrap-grid.css'
import './vendor/bootstrap/css/bootstrap-grid.min.css'
import './vendor/bootstrap/css/bootstrap-grid.rtl.css'
import './vendor/bootstrap/css/bootstrap-grid.rtl.min.css'
import './vendor/bootstrap/css/bootstrap-reboot.css'
import './vendor/bootstrap/css/bootstrap-reboot.min.css'
import './vendor/bootstrap/css/bootstrap-reboot.rtl.css'
import './vendor/bootstrap/css/bootstrap-utilities.css'
import './vendor/bootstrap-icons/bootstrap-icons.json'
import './vendor/boxicons/css/animations.css'
import './vendor/boxicons/css/boxicons.css'
import './vendor/boxicons/css/boxicons.min.css'
import './vendor/boxicons/css/transformations.css'
import './vendor/glightbox/css/glightbox.css'
import './vendor/glightbox/css/glightbox.min.css'
import './vendor/glightbox/css/plyr.css'
import './vendor/glightbox/css/plyr.min.css'
import './vendor/swiper/swiper-bundle.min.css'
import './vendor/swiper/swiper-bundle.min.js'
// import './vendor/isotope-layout/isotope.pkgd'


// const inter = Inter({ subsets: ['latin'] })

// export const metadata  = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"/>

      </head>
      <body className={""}>{children}</body>
    </html>
  )
}
